spring:
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:./db/h2
    driver-class-name: org.h2.Driver
    username: user
    password: pass
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: pass
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        trace: false

server:
  port: 8081
